/* Original review questions based on the instructor's supplied Freberg 2e materials. */
window.PR_CONTENT = {
  chapters: [
    {id:1, short:'PR foundations', title:'An Introduction to Public Relations', color:'#bdf269'},
    {id:2, short:'History & models', title:'Historical Contexts and Today’s Practices', color:'#96c6ff'},
    {id:3, short:'Ethics & law', title:'Ethics and the Law', color:'#ffc38d'},
    {id:4, short:'DEI & belonging', title:'Diversity, Equity, Inclusion, and Belonging', color:'#d5b4ff'},
    {id:5, short:'Research', title:'Research and Evidence-Based Practices', color:'#79e1d3'}
  ],
  warmups: [
    {id:'w1',chapter:1,kind:'mc',topic:'The purpose of PR',prompt:'Which goal is at the heart of public relations?',options:['Securing favorable coverage at any cost','Building mutually beneficial relationships with publics','Replacing every other communication function','Controlling every audience response'],correct:1,answer:'Building mutually beneficial relationships with publics.',explanation:'PR manages relationships between organizations and the people or groups important to them. Publicity can support that work, but it is only one part of it.',slides:[3,4,7],section:'What Is Public Relations?'},
    {id:'w2',chapter:2,kind:'mc',topic:'An ethical tradition',prompt:'Which historical PR figure is associated with principles such as telling the truth, listening to stakeholders, and backing claims with action?',options:['Edward Bernays','P. T. Barnum','Arthur W. Page','Ivy Lee'],correct:2,answer:'Arthur W. Page.',explanation:'The Page principles connect corporate communication with responsible behavior. What an organization does must support what it says.',slides:[9],section:'Arthur W. Page and the Page Principles'},
    {id:'w3',chapter:3,kind:'mc',topic:'Professional values',prompt:'Which set contains only values listed in the PRSA code in Chapter 3?',options:['Advocacy, honesty, and fairness','Secrecy, loyalty, and publicity','Expertise, popularity, and secrecy','Independence, speed, and profit'],correct:0,answer:'Advocacy, honesty, and fairness.',explanation:'The six values listed in the materials are advocacy, honesty, expertise, independence, loyalty, and fairness.',slides:[6],section:'The Code of the Public Relations Society of America (PRSA)'},
    {id:'w4',chapter:4,kind:'mc',topic:'Representation',prompt:'A campaign includes people with different backgrounds, identities, and experiences. Which concept most directly describes that variety?',options:['Equity','Monitoring','Puffery','Diversity'],correct:3,answer:'Diversity.',explanation:'Diversity concerns differences and representation within a group. Inclusion and belonging also require attention to participation and people’s experiences.',slides:[4,8],section:'Diversity; The Differences Between Diversity, Equity, Inclusion, and Belonging'},
    {id:'w5',chapter:5,kind:'mc',topic:'Research in PR',prompt:'When should research inform a PR campaign?',options:['Only after the campaign ends','Only when a campaign receives criticism','During planning and evaluation, and as the campaign develops','Only when a client asks for a survey'],correct:2,answer:'During planning and evaluation, and as the campaign develops.',explanation:'Research helps identify audiences, guide messages and strategy, track what is happening, and evaluate results.',slides:[3,5,6],section:'The Role of Research in Public Relations'}
  ],
  questions: [
    {id:'c1-100',chapter:1,points:100,kind:'mc',topic:'Publics',prompt:'In PR, a “public” is best understood as which of the following?',options:['Everyone in the world, treated as one identical audience','Only the people who buy a product','An audience with shared characteristics or interests relevant to the organization','Only journalists covering the organization'],correct:2,answer:'An audience with shared characteristics or interests relevant to the organization.',explanation:'Publics can include employees, community members, media, government, and customers. PR identifies relevant groups so communication fits their needs.',slides:[4,5],section:'We Identify Publics'},
    {id:'c1-200',chapter:1,points:200,kind:'mc',topic:'Stakeholders',prompt:'Which is an example of an internal stakeholder for a university?',options:['A journalist at a local newspaper','A faculty member employed by the university','A nearby business owner','A prospective student’s parent'],correct:1,answer:'A faculty member employed by the university.',explanation:'Stakeholders have a vested interest in an organization. Employees are internal stakeholders; people outside the organization can also have important interests in it.',slides:[6],section:'We Focus on Stakeholders'},
    {id:'c1-300',chapter:1,points:300,kind:'mc',topic:'Paid and earned media',scenario:true,prompt:'A local newspaper independently covers a nonprofit’s event after receiving a pitch. The nonprofit pays nothing for the placement. What type of media exposure is this?',options:['Earned media','Paid advertising','A purchased endorsement','An internal employee message'],correct:0,answer:'Earned media.',explanation:'The outlet makes an editorial choice to cover the story. Paid media involves purchasing placement. PR can work across different media types; it is not limited to earned coverage.',slides:[15,16,17],section:'How Do We Work With Professionals in Related Fields?'},
    {id:'c1-400',chapter:1,points:400,kind:'short',topic:'PR and marketing',scenario:true,prompt:'A retailer’s marketing team wants more purchases. Its PR team also meets with employees and neighbors about the store’s impact. What broader focus does the PR work illustrate?',answer:'Building and maintaining relationships with multiple publics, including people who are not customers.',explanation:'The chapter contrasts marketing’s purchase focus with PR’s focus on relationships and communication between organizations and publics. The two fields can work together.',rubric:['Identifies relationship building as the PR focus.','Recognizes employees or neighbors as relevant publics beyond customers.'],slides:[18],section:'We Work With Marketing Professionals'},
    {id:'c1-500',chapter:1,points:500,kind:'short',topic:'Research and creativity',scenario:true,prompt:'Students ignore a campus event campaign. Before making a new slogan, name one useful research action and explain how its findings could improve the message.',answer:'For example, interview students about why they did not attend, then use their concerns to make the message more relevant.',explanation:'Research provides audience insights. Creative work applies those insights through messaging, content, or storytelling. Accept other reasonable actions, such as a survey or analysis of audience feedback, when linked to a specific communication decision.',rubric:['Names a relevant way to gather audience information.','Explains how the findings would guide a message or channel decision.'],slides:[11,12],section:'We Conduct Research; We Think Creatively'},

    {id:'c2-100',chapter:2,points:100,kind:'mc',topic:'Press agentry',prompt:'Which PR model primarily seeks attention and publicity through one-way communication?',options:['Two-way symmetrical','Public information','Two-way asymmetrical','Press agentry and publicity'],correct:3,answer:'Press agentry and publicity.',explanation:'This model emphasizes getting attention and generating publicity. In the chapter’s model comparison, it does not rely on formal audience research.',slides:[4],section:'The Press Agentry and Publicity Model'},
    {id:'c2-200',chapter:2,points:200,kind:'mc',topic:'Public information',scenario:true,prompt:'A city posts an accurate notice about road closures. It distributes information without seeking audience input in this activity. Which model fits best?',options:['Two-way symmetrical','Public information','Two-way asymmetrical','Press agentry and publicity'],correct:1,answer:'Public information.',explanation:'The public information model emphasizes truthful, useful information delivered in one direction. Accuracy separates its central emphasis from simply seeking attention.',slides:[5],section:'The Public Information Model'},
    {id:'c2-300',chapter:2,points:300,kind:'mc',topic:'Two-way asymmetry',scenario:true,prompt:'A company surveys residents, then uses the answers only to make its existing plan more persuasive. The company will not change the plan. Which model fits best?',options:['Two-way asymmetrical','Public information','Two-way symmetrical','Press agentry and publicity'],correct:0,answer:'Two-way asymmetrical.',explanation:'Audience feedback and formal research are present, but the organization uses them mainly to persuade the public in its own interest. Feedback alone does not establish symmetry.',slides:[6,7],section:'The Two-Way Asymmetrical Communication Model'},
    {id:'c2-400',chapter:2,points:400,kind:'mc',topic:'Two-way symmetry',scenario:true,prompt:'A university meets with neighbors about event noise. Both sides discuss their needs, and the university changes event hours to reach a workable agreement. Which model fits best?',options:['Press agentry and publicity','Two-way asymmetrical','Two-way symmetrical','Public information'],correct:2,answer:'Two-way symmetrical.',explanation:'The organization listens, negotiates, and is willing to change its behavior. The goal is a mutually beneficial result, rather than only persuading the audience.',slides:[8],section:'The Two-Way Symmetrical Communication Model'},
    {id:'c2-500',chapter:2,points:500,kind:'short',topic:'Feedback is not enough',scenario:true,prompt:'A brand says, “We use two-way symmetrical communication because our posts allow comments.” Why is that evidence insufficient, and what additional action would support its claim?',answer:'Comments allow feedback, but symmetry also requires meaningful listening and willingness to adapt. The brand could use audience input to negotiate or change a policy for mutual benefit.',explanation:'Both two-way models can include feedback. The key distinction is how power and influence operate: research used only to persuade is asymmetrical, while mutual adjustment supports symmetry.',rubric:['Explains that allowing feedback alone does not establish symmetry.','Gives a reasonable example of listening followed by mutual adjustment or negotiation.'],slides:[6,8],section:'The Two-Way Asymmetrical and Symmetrical Communication Models'},

    {id:'c3-100',chapter:3,points:100,kind:'mc',topic:'Disclosure',scenario:true,prompt:'A creator receives payment to promote a brand. Which action best follows the ethical guidance in Chapter 3?',options:['Describe the post as an unpaid personal discovery','Disclose the partnership only if someone complains','Avoid mentioning the relationship because followers can guess','Clearly disclose the paid relationship'],correct:3,answer:'Clearly disclose the paid relationship.',explanation:'Transparent communication about payment and affiliations lets audiences understand the relationship behind a message. This question applies the course’s ethical guidance.',slides:[12,13],section:'Disclosing Your Associations; Being Honest About Influencer Relations'},
    {id:'c3-200',chapter:3,points:200,kind:'mc',topic:'Greenwashing',scenario:true,prompt:'A company spends heavily promoting itself as environmentally responsible while making little meaningful change to its sustainability practices. Which term fits?',options:['Greenwashing','Audience segmentation','Public information','Equity'],correct:0,answer:'Greenwashing.',explanation:'Greenwashing creates a misleading impression of environmental responsibility. The problem is the gap between the promoted image and the organization’s practices.',slides:[11],section:'Potential Situations: Greenwashing'},
    {id:'c3-300',chapter:3,points:300,kind:'mc',topic:'Astroturfing',scenario:true,prompt:'A company secretly funds a campaign that presents itself as an independent grassroots citizens’ movement. Which term fits?',options:['Earned media','Belonging','Astroturfing','Primary research'],correct:2,answer:'Astroturfing.',explanation:'Astroturfing conceals the sponsor and makes organized messaging appear to come independently from members of the public.',slides:[11],section:'Potential Situations: Astroturfing'},
    {id:'c3-400',chapter:3,points:400,kind:'short',topic:'Libel and slander',prompt:'Using the basic distinction taught in Chapter 3, match these terms: a written false statement that harms someone’s reputation; an oral false statement that harms someone’s reputation.',answer:'Written: libel. Oral: slander. Both fall under defamation.',explanation:'The course introduces libel as written or printed falsehood and slander as oral falsehood. This is a vocabulary distinction, not a complete test for legal liability.',rubric:['Correctly matches the written statement to libel.','Correctly matches the oral statement to slander.'],slides:[19,20],section:'Libel; Slander'},
    {id:'c3-500',chapter:3,points:500,kind:'short',topic:'Puffery and deception',scenario:true,prompt:'Compare two fictional claims: “The most amazing campus café!” and “Every cup contains 50% less sugar,” when that specific claim is false. Which illustrates puffery, and which illustrates deception?',answer:'“The most amazing campus café!” illustrates puffery. The false 50% less sugar claim illustrates deception.',explanation:'Puffery is broad, subjective exaggeration. A concrete factual claim can mislead an audience when it is false. Classifying a real dispute would require more context; these examples illustrate the course distinction.',rubric:['Identifies the subjective superlative as puffery.','Identifies the false measurable claim as deception and explains the difference.'],slides:[21,22],section:'Deception; Puffery'},

    {id:'c4-100',chapter:4,points:100,kind:'mc',topic:'Equity',prompt:'Which statement best describes equity in Chapter 4?',options:['Giving everyone exactly the same resources regardless of need','Providing different resources people need to thrive and succeed','Assuming representation automatically creates belonging','Using one message for every audience'],correct:1,answer:'Providing different resources people need to thrive and succeed.',explanation:'Equity responds to different needs and barriers. Equality emphasizes equal access or resources for everyone.',slides:[5,8],section:'Equity; The Differences Between Diversity, Equity, Inclusion, and Belonging'},
    {id:'c4-200',chapter:4,points:200,kind:'mc',topic:'Inclusion',scenario:true,prompt:'An agency recruits people from different backgrounds, but only a small inner circle can influence campaign decisions. What is the clearest next step toward inclusion?',options:['Feature the new hires in a photo without changing the process','Assume recruitment has completed the work','Require everyone to use the same viewpoint','Give team members meaningful opportunities to contribute'],correct:3,answer:'Give team members meaningful opportunities to contribute.',explanation:'Representation is important, but inclusion also concerns how people are treated and whether their perspectives enter the work.',slides:[6,8],section:'Inclusion; The Differences Between Diversity, Equity, Inclusion, and Belonging'},
    {id:'c4-300',chapter:4,points:300,kind:'mc',topic:'Belonging',scenario:true,prompt:'A team member says, “I feel welcomed here, my voice matters, and I can contribute to decisions.” Which concept most directly captures that experience?',options:['Belonging','Audience segmentation','Equality','Media monitoring'],correct:0,answer:'Belonging.',explanation:'Belonging involves feeling welcomed and having a voice, place, and position in a community. It is not guaranteed just because a group is diverse.',slides:[7,8],section:'Belonging'},
    {id:'c4-400',chapter:4,points:400,kind:'short',topic:'Accessible communication',scenario:true,prompt:'A campaign includes a video with spoken instructions and an important information graphic. Name one accessibility improvement for each.',answer:'Add accurate captions to the video. Provide meaningful alternative text or an equivalent text description for the graphic.',explanation:'The chapter specifically identifies closed captions for videos and alternative text for images. Accessible communication helps people receive and use the message.',rubric:['Names captions or an equivalent accessible text version for the video.','Names meaningful alt text or an equivalent text description for the graphic.'],slides:[15],section:'Content, Messaging, and Opportunities Must Be Accessible for All'},
    {id:'c4-500',chapter:4,points:500,kind:'short',topic:'Commitment into practice',scenario:true,prompt:'An agency publishes an inclusion statement, but its hiring, mentoring, and decision-making practices remain unchanged. Give two concrete actions that would put its statement into practice.',answer:'For example, broaden recruitment partnerships and create funded mentoring opportunities with clear access for employees who have been excluded.',explanation:'Accept concrete actions involving hiring, leadership, training, mentorship, accessibility, resources, or ongoing evaluation. The chapter emphasizes implementing and reviewing commitments.',rubric:['Names one specific change to an organizational practice.','Names a second distinct action that supports participation, access, or accountability.'],slides:[14,17,22,23,25],section:'Hiring Practices Must Embrace DEI&B; We Need to Implement Principles and Practices'},

    {id:'c5-100',chapter:5,points:100,kind:'mc',topic:'Primary and secondary research',scenario:true,prompt:'A PR team interviews students for its own new study and also reviews an existing published report. How should it classify these activities?',options:['Both are secondary research','Interviews are secondary; the report is primary','Interviews are primary; the report is secondary','Both are informal research by definition'],correct:2,answer:'The new interviews are primary research; reviewing the existing report is secondary research.',explanation:'Primary research gathers original information for the team’s study. Secondary research uses material that already exists.',slides:[14],section:'Primary and Secondary Research'},
    {id:'c5-200',chapter:5,points:200,kind:'mc',topic:'Mixed methods',scenario:true,prompt:'A team first uses open-ended interviews to understand concerns, then a numerical survey to examine how common those concerns are. What approach combines these methods?',options:['Secondary research only','Mixed-methods research','Qualitative research only','An experiment by definition'],correct:1,answer:'Mixed-methods research.',explanation:'The project combines qualitative exploration with quantitative measurement. A survey does not automatically constitute an experiment.',slides:[15,16,17],section:'Qualitative, Quantitative, and Mixed Methods'},
    {id:'c5-300',chapter:5,points:300,kind:'mc',topic:'Outputs and outcomes',scenario:true,prompt:'A campaign produces 12 social posts. Later, 60 people sign up for the program promoted by the campaign. Which pair correctly identifies an output and an outcome?',options:['The posts are an output; the sign-ups are a behavioral outcome','The posts are an outcome; the sign-ups are an output','Both are outputs because they are numbers','Both are outcomes because they occur during a campaign'],correct:0,answer:'The posts are an output; the sign-ups are a behavioral outcome.',explanation:'Outputs describe communication produced or distributed. Outcomes concern audience response or change. Counting sign-ups alone does not prove the campaign caused them.',slides:[9],section:'Outputs and Outcomes'},
    {id:'c5-400',chapter:5,points:400,kind:'short',topic:'Reliability and validity',scenario:true,prompt:'A team claims to measure trust by asking only whether people recognize a logo. The item gives consistent results. Which concept is about consistency, and what separate measurement concern remains?',answer:'Reliability concerns consistency. Validity remains a concern because recognizing a logo does not establish that someone trusts the organization.',explanation:'A measure can be consistent while measuring the wrong concept. Validity asks whether it actually measures what it is supposed to measure.',rubric:['Connects consistent results with reliability.','Identifies validity as the concern and distinguishes recognition from trust.'],slides:[11],section:'The Concepts of Reliability and Validity'},
    {id:'c5-500',chapter:5,points:500,kind:'short',topic:'Understanding an audience',scenario:true,prompt:'A campaign team knows that its audience is 18–24 years old but still does not understand why people would participate. Name one demographic fact already known, one psychographic question to investigate, and a useful research method.',answer:'Demographic: age. Psychographic question: what values, interests, or motivations shape participation? Method: interviews, focus groups, or a suitable survey.',explanation:'Demographics describe population characteristics. Psychographics examine attributes such as values, attitudes, and interests. Research helps turn these details into a useful picture of an audience.',rubric:['Identifies age as demographic.','Proposes a question about values, attitudes, interests, or motivations.','Names a method that can reasonably answer that question.'],slides:[8,15,16],section:'Audience Segmentation; Qualitative, Quantitative, and Mixed Methods'}
  ],
  final: {
    id:'final',chapter:0,kind:'short',topic:'The campus campaign',scenario:true,
    prompt:'A campus club wants more students to attend its events. Students say the events feel unwelcoming, and campaign videos have no captions. A paid student creator promotes the events without disclosing the partnership. Propose a brief PR response using all five parts below.',
    tasks:['Identify a relevant public and one way to learn about its concerns.','Explain how the club could use two-way symmetrical communication.','Address the ethical problem in the promotion.','Name a concrete inclusion or accessibility improvement.','Choose an audience outcome to evaluate, beyond the number of posts.'],
    answer:'Interview students who feel excluded; use a listening session to jointly revise event plans; disclose the paid partnership; caption the videos and address barriers to participation; evaluate attendance or participants’ reported sense of belonging.',
    explanation:'Many responses can work. The important connection is between audience evidence, mutual adjustment, transparent communication, practical inclusion, and evaluation of audience response.',
    rubric:['A relevant public and an appropriate research method.','Listening plus willingness to change plans for mutual benefit.','Clear disclosure of the paid partnership.','A specific improvement to inclusion or accessibility.','A meaningful audience outcome, such as participation or reported belonging.'],
    grading:'Count a team’s response as successful when at least 4 of the 5 elements are sound. Accept equivalent examples and wording.',
    sources:[{chapter:1,slides:[4,5,11]},{chapter:2,slides:[8]},{chapter:3,slides:[12,13]},{chapter:4,slides:[7,15]},{chapter:5,slides:[9,14,15]}]
  }
};
